name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v5
      with:
        fetch-depth: 2

    - name: Install Markdownlint-cli
      run: |
        npm install -g markdownlint-cli

    - name: Lint
      run: |
        bash ./wiki-tools/lint.sh 2>&1 | tee lint-report.txt

    - name: Upload lint report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: lint-report.txt
